kind = "web"
previewPath = "/"
title = "Mieszkanie na sprzedaż"
version = "1.0.0"
id = "artifacts/mieszkanie"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20481

[services.development]
run = "pnpm --filter @workspace/mieszkanie run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mieszkanie", "run", "build" ]
publicDir = "artifacts/mieszkanie/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20481"
BASE_PATH = "/"
